apiVersion: v1
kind: ConfigMap
metadata:
  name: obvestila-config
  namespace: production
data:
  LOG_LEVEL: "INFO"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  RESEND_FROM_EMAIL: "noreply@prpo.timhrovat.com"
