apiVersion: v1
kind: Service
metadata:
  name: obvestila
  namespace: production
  labels:
    app: obvestila
  annotations:
    cloud.google.com/backend-config: '{"default": "obvestila-backendconfig"}'
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: obvestila
